-- Löschung der Tabellen
DROP TABLE Lieferung;
DROP TABLE Lieferant;
DROP TABLE Lager;
DROP TABLE Reservierung;
DROP TABLE Teilestruktur;
DROP TABLE Auftragsposition;
DROP TABLE Auftrag;
DROP TABLE Artikel;
DROP TABLE Kunde;
DROP TABLE Personal;



-- ----------------------------------------------------------------
-- Erstellung der Tabellen

CREATE TABLE Lieferant (
    Nr INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name CHAR(30) NOT NULL,
    Strasse CHAR(30),
    PLZ INTEGER,
    Ort CHAR(20),
    Sperre CHAR(1)
);

CREATE TABLE Artikel (
    Anr INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Bezeichnung CHAR(35) NOT NULL,
    Netto NUMERIC(7,2),
    Steuer NUMERIC(7,2),
    Preis NUMERIC(7,2),
    Farbe CHAR(10),
    Mass CHAR(15),
    Einheit CHAR(2),
    Typ CHAR(1)
);

CREATE TABLE Lieferung (
    Anr INTEGER NOT NULL,
    Liefnr INTEGER NOT NULL,
    Lieferzeit SMALLINT,
    Nettopreis NUMERIC(7,2),
    Bestellt SMALLINT,
    PRIMARY KEY (Anr, Liefnr),
    FOREIGN KEY (Anr) REFERENCES Artikel(Anr),
    FOREIGN KEY (Liefnr) REFERENCES Lieferant(Nr)
);

CREATE TABLE Lager (
    Artnr INTEGER PRIMARY KEY,
    Lagerort CHAR(20),
    Bestand SMALLINT,
    Mindest SMALLINT,
    Reserviert SMALLINT,
    Bestellt SMALLINT
);

CREATE TABLE Reservierung (
    Posnr INTEGER NOT NULL,
    Artnr INTEGER NOT NULL,
    Anzahl SMALLINT,
    PRIMARY KEY (Posnr, Artnr),
    FOREIGN KEY (Artnr) REFERENCES Artikel(Anr)
);

CREATE TABLE Kunde (
    Nr INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name CHAR(30) NOT NULL,
    Strasse CHAR(30),
    PLZ INTEGER,
    Ort CHAR(20),
    Sperre CHAR(1)
);

CREATE TABLE Personal (
    Persnr INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name CHAR(30) NOT NULL,
    Strasse CHAR(30),
    PLZ INTEGER,
    Ort CHAR(20),
    GebDatum DATE,
    Stand CHAR(5),
    Vorgesetzter INTEGER,
    Gehalt NUMERIC(8,2),
    Beurteilung CHAR(1),
    Aufgabe CHAR(18),
    FOREIGN KEY (Vorgesetzter) REFERENCES Personal(Persnr)
);

CREATE TABLE Auftrag (
    AufNr INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Datum DATE NOT NULL,
    KundNr INTEGER,
    Persnr INTEGER,
    FOREIGN KEY (KundNr) REFERENCES Kunde(Nr),
    FOREIGN KEY (Persnr) REFERENCES Personal(Persnr)
);

CREATE TABLE Auftragsposition (
    PosNr INTEGER NOT NULL,
    AufNr INTEGER NOT NULL,
    Artnr INTEGER NOT NULL,
    Anzahl SMALLINT,
    Gesamtreis NUMERIC(7,2),
    PRIMARY KEY (PosNr),
    FOREIGN KEY (AufNr) REFERENCES Auftrag(AufNr),
    FOREIGN KEY (Artnr) REFERENCES Artikel(Anr)
);

CREATE TABLE Teilestruktur (
    Artnr INTEGER NOT NULL,
    Einzelnr INTEGER NOT NULL,
    Anzahl SMALLINT,
    Einheit CHAR(2),
    PRIMARY KEY (Artnr, Einzelnr),
    FOREIGN KEY (Artnr) REFERENCES Artikel(Anr)
);


-- ----------------------------------------------------------------
-- 5 Datensätze für jede Tabelle

INSERT INTO Lieferant (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Lieferant A', 'Musterstraße 1', 12345, 'Berlin', 'N');
INSERT INTO Lieferant (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Lieferant B', 'Hauptstraße 7', 54321, 'Hamburg', 'N');
INSERT INTO Lieferant (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Lieferant C', 'Nebenstraße 5', 98765, 'München', 'Y');
INSERT INTO Lieferant (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Lieferant D', 'Bahnhofstraße 10', 87654, 'Köln', 'N');
INSERT INTO Lieferant (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Lieferant E', 'Ringstraße 22', 65432, 'Stuttgart', 'N');

INSERT INTO Artikel (Bezeichnung, Netto, Steuer, Preis, Farbe, Mass, Einheit, Typ) VALUES ('Stuhl', 50.00, 10.00, 60.00, 'Rot', '50x50x100', 'ST', 'A');
INSERT INTO Artikel (Bezeichnung, Netto, Steuer, Preis, Farbe, Mass, Einheit, Typ) VALUES ('Tisch', 100.00, 20.00, 120.00, 'Weiß', '120x80x75', 'ST', 'B');
INSERT INTO Artikel (Bezeichnung, Netto, Steuer, Preis, Farbe, Mass, Einheit, Typ) VALUES ('Lampe', 30.00, 6.00, 36.00, 'Schwarz', '15x15x50', 'ST', 'C');
INSERT INTO Artikel (Bezeichnung, Netto, Steuer, Preis, Farbe, Mass, Einheit, Typ) VALUES ('Sofa', 200.00, 40.00, 240.00, 'Blau', '200x90x75', 'ST', 'A');
INSERT INTO Artikel (Bezeichnung, Netto, Steuer, Preis, Farbe, Mass, Einheit, Typ) VALUES ('Regal', 80.00, 16.00, 96.00, 'Braun', '180x60x30', 'ST', 'B');

INSERT INTO Lieferung (Anr, Liefnr, Lieferzeit, Nettopreis, Bestellt) VALUES (1, 1, 7, 45.00, 100);
INSERT INTO Lieferung (Anr, Liefnr, Lieferzeit, Nettopreis, Bestellt) VALUES (2, 2, 10, 95.00, 50);
INSERT INTO Lieferung (Anr, Liefnr, Lieferzeit, Nettopreis, Bestellt) VALUES (3, 3, 14, 28.00, 20);
INSERT INTO Lieferung (Anr, Liefnr, Lieferzeit, Nettopreis, Bestellt) VALUES (4, 4, 21, 185.00, 10);
INSERT INTO Lieferung (Anr, Liefnr, Lieferzeit, Nettopreis, Bestellt) VALUES (5, 5, 30, 70.00, 25);

INSERT INTO Lager (Artnr, Lagerort, Bestand, Mindest, Reserviert, Bestellt) VALUES (1, 'Berlin', 200, 50, 20, 100);
INSERT INTO Lager (Artnr, Lagerort, Bestand, Mindest, Reserviert, Bestellt) VALUES (2, 'Hamburg', 150, 30, 10, 50);
INSERT INTO Lager (Artnr, Lagerort, Bestand, Mindest, Reserviert, Bestellt) VALUES (3, 'München', 100, 20, 5, 25);
INSERT INTO Lager (Artnr, Lagerort, Bestand, Mindest, Reserviert, Bestellt) VALUES (4, 'Köln', 80, 10, 8, 15);
INSERT INTO Lager (Artnr, Lagerort, Bestand, Mindest, Reserviert, Bestellt) VALUES (5, 'Stuttgart', 120, 25, 12, 30);

INSERT INTO Reservierung (Posnr, Artnr, Anzahl) VALUES (1, 1, 5);
INSERT INTO Reservierung (Posnr, Artnr, Anzahl) VALUES (2, 2, 10);
INSERT INTO Reservierung (Posnr, Artnr, Anzahl) VALUES (3, 3, 15);
INSERT INTO Reservierung (Posnr, Artnr, Anzahl) VALUES (4, 4, 8);
INSERT INTO Reservierung (Posnr, Artnr, Anzahl) VALUES (5, 5, 12);

INSERT INTO Kunde (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Max Mustermann', 'Musterweg 1', 12345, 'Berlin', 'N');
INSERT INTO Kunde (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Erika Musterfrau', 'Hauptplatz 3', 54321, 'Hamburg', 'N');
INSERT INTO Kunde (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Hans Beispiel', 'Beispielgasse 5', 98765, 'München', 'Y');
INSERT INTO Kunde (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Petra Test', 'Teststraße 7', 87654, 'Köln', 'N');
INSERT INTO Kunde (Name, Strasse, PLZ, Ort, Sperre) VALUES ('Uwe Proband', 'Probandweg 9', 65432, 'Stuttgart', 'N');

INSERT INTO Personal (Name, Strasse, PLZ, Ort, GebDatum, Stand, Vorgesetzter, Gehalt, Beurteilung, Aufgabe) VALUES ('Karl Schmidt', 'Blumenstraße 1', 12345, 'Berlin', TO_DATE('1980-05-15', 'YYYY-MM-DD'), 'MGR', NULL, 5000.00, 'A', 'Manager');
INSERT INTO Personal (Name, Strasse, PLZ, Ort, GebDatum, Stand, Vorgesetzter, Gehalt, Beurteilung, Aufgabe) VALUES ('Lisa Müller', 'Sonnenallee 2', 54321, 'Hamburg', TO_DATE('1990-08-20', 'YYYY-MM-DD'), 'EMP', 1, 3200.00, 'B', 'Vertrieb');
INSERT INTO Personal (Name, Strasse, PLZ, Ort, GebDatum, Stand, Vorgesetzter, Gehalt, Beurteilung, Aufgabe) VALUES ('Tom Fischer', 'Hafenstraße 4', 98765, 'München', TO_DATE('1975-03-10', 'YYYY-MM-DD'), 'EMP', 1, 3500.00, 'C', 'Logistik');
INSERT INTO Personal (Name, Strasse, PLZ, Ort, GebDatum, Stand, Vorgesetzter, Gehalt, Beurteilung, Aufgabe) VALUES ('Eva Bauer', 'Hauptstraße 12', 87654, 'Köln', TO_DATE('1985-12-25', 'YYYY-MM-DD'), 'EMP', 2, 3100.00, 'B', 'Kundenservice');
INSERT INTO Personal (Name, Strasse, PLZ, Ort, GebDatum, Stand, Vorgesetzter, Gehalt, Beurteilung, Aufgabe) VALUES ('Frank Weber', 'Ringstraße 8', 65432, 'Stuttgart', TO_DATE('1992-07-05', 'YYYY-MM-DD'), 'EMP', 1, 2800.00, 'B', 'Lager');

INSERT INTO Auftrag (Datum, KundNr, Persnr) VALUES (TO_DATE('2023-01-10', 'YYYY-MM-DD'), 1, 2);
INSERT INTO Auftrag (Datum, KundNr, Persnr) VALUES (TO_DATE('2023-02-15', 'YYYY-MM-DD'), 2, 3);
INSERT INTO Auftrag (Datum, KundNr, Persnr) VALUES (TO_DATE('2023-03-20', 'YYYY-MM-DD'), 3, 4);
INSERT INTO Auftrag (Datum, KundNr, Persnr) VALUES (TO_DATE('2023-04-25', 'YYYY-MM-DD'), 4, 5);
INSERT INTO Auftrag (Datum, KundNr, Persnr) VALUES (TO_DATE('2023-05-30', 'YYYY-MM-DD'), 5, 1);

INSERT INTO Auftragsposition (PosNr, AufNr, Artnr, Anzahl, Gesamtreis) VALUES (1, 1, 1, 5, 300.00);
INSERT INTO Auftragsposition (PosNr, AufNr, Artnr, Anzahl, Gesamtreis) VALUES (2, 2, 2, 10, 600.00);
INSERT INTO Auftragsposition (PosNr, AufNr, Artnr, Anzahl, Gesamtreis) VALUES (3, 3, 3, 3, 108.00);
INSERT INTO Auftragsposition (PosNr, AufNr, Artnr, Anzahl, Gesamtreis) VALUES (4, 4, 4, 2, 480.00);
INSERT INTO Auftragsposition (PosNr, AufNr, Artnr, Anzahl, Gesamtreis) VALUES (5, 5, 5, 1, 96.00);

INSERT INTO Teilestruktur (Artnr, Einzelnr, Anzahl, Einheit) VALUES (1, 2, 5, 'ST');
INSERT INTO Teilestruktur (Artnr, Einzelnr, Anzahl, Einheit) VALUES (2, 3, 3, 'ST');
INSERT INTO Teilestruktur (Artnr, Einzelnr, Anzahl, Einheit) VALUES (3, 4, 2, 'ST');
INSERT INTO Teilestruktur (Artnr, Einzelnr, Anzahl, Einheit) VALUES (4, 5, 1, 'ST');
INSERT INTO Teilestruktur (Artnr, Einzelnr, Anzahl, Einheit) VALUES (5, 1, 4, 'ST');

-- ----------------------------------------------------------------
-- Anzeigen der Tabellen

-- SELECT * FROM Lieferant;
-- SELECT * FROM Artikel;
-- SELECT * FROM Lieferung;
-- SELECT * FROM Lager;
-- SELECT * FROM Reservierung;
-- SELECT * FROM Kunde;
-- SELECT * FROM Personal;
-- SELECT * FROM Auftrag;
-- SELECT * FROM Auftragsposition;
-- SELECT * FROM Teilestruktur;


-- ----------------------------------------------------------------


    